# Generated by Django 4.1 on 2023-07-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.IntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completado', to='backend.evaluacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completado', to='backend.persona')),
            ],
        ),
    ]
