# Generated by Django 4.1 on 2023-07-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='dificultad',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
