# Generated by Django 4.1 on 2023-07-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_resultado_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='tag',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
